### PR TITLE
Allow for multiple `schwifty()` calls, various knex-related features and fixes

### LINKED ISSUE #7: Allow passing of knex instance in addition to knex config
The user should be completely in charge of the version of knex they want to use.  I don't mind falling back to generating a knex instance as we currently do.

### LINKED ISSUE #9: Should allow specifying models / knex in multiple calls to `srv.schwifty()`
Instead it errors out when you call `server.schwifty()` multiple times, even to specify a knex instance that isn't set yet or to add new models.

```
Root server must have a knex instance before adding models to this plugin without a knex instance.
```

### LINKED ISSUE #10: During teardown, should not call `knex.destroy()` on the same instance multiple times
`knex.destroy()` is called on the same instance multiple times when multiple plugins use the same knex instance.  Seems like one of those things that could cause unforeseen problems, esp as connections are drained in parallel.

### LINKED ISSUE #11: Plugins without models should not see models when calling `srv.models(false)`

### LINKED ISSUE #12: Plugin's knex instance should default to the root server's
This is both,

1. when `Model.knexBind()`ing during init and,
2. when calling `request.knex()` and `server.knex()`.

### PR DESCRIPTION
**Pull request by devinivy**
Closes #7, fixes #9, fixes #10, fixes #11, closes #12!  Will summarize better later.

### CODE REVIEW

**Comment by devinivy** [comment]
Yeah, there's some missing coverage!

File: lib/index.js [hunk 1]
```diff
@@ -79,19 +79,21 @@ internals.registrationConfig = (options) => {
...
 
         const models = knexGroup.models;
+        const knex = knexGroup.knex || rootKnex;
 
         models.forEach((modelName) => {
 
-            const model = rootCollector.models[modelName];
-            const modelKnexed = model.bindKnex(knexGroup.knex);
-            rootCollector.models[modelName] = modelKnexed;
+            const Model = collector.models[modelName];
```
Comment (mattboutet) [inline lib/index.js:94]: I haven't completely wrapped my brain around this yet, but it feels a little weird.  What if there's a collision between `modelName`s in different `knexGroups`?  (can that even happen, or would it be caught before it got here?).

My brain's still on express' non-deterministic routing, so I'm probably just being paranoid.

Comment (mattboutet) [reply lib/index.js:94]: LOL, page down answered my question.  disregard.

**Review by mattboutet — APPROVED** [review]
LGTM, can't wait to take this for a spin.

**Comment by devinivy** [comment]
@WilliamSWoodruff do you think you'll have time to review this?

**Comment by wswoodruff** [comment]
@devinivy Unfortunately I think I won't til tomorrow, I say go ahead and merge it!

**Comment by devinivy** [comment]
There's no particular rush.  I'll leave this here til Wednesday at the latest.  If I want to develop on top of this at some point in my free time, maybe I'll just merge it :P

If you don't get time to review it, no sweat!

File: lib/index.js [hunk 2]
```diff
@@ -79,19 +79,21 @@ internals.registrationConfig = (options) => {
     return config;
 };
 
-internals.initialize = function (server, next) {
+internals.initialize = (server, next) => {
 
-    const rootCollector = internals.state(server.root).collector;
+    const collector = internals.state(server.root).collector;
+    const rootKnex = Hoek.reach(collector, 'knexGroup.knex') || null;
```
Comment (wswoodruff) [inline lib/index.js:85]: I think the root knex instance is on the internals.state(server.root) object

Comment (devinivy) [reply lib/index.js:85]: Not anymore– now the root knex instance is the one set by either specifying `knex` during plugin registration or calling `schwifty()` on the root server.  That means it's set the same as in any plugin, on `srv.realm.plugins.schwifty.knexGroup.knex`.

Comment (wswoodruff) [reply lib/index.js:85]: I might not be understanding it correctly, but Line 85 is reaching into collector for fullpath: `internals.state(server.root).collector.knexGroup.knex`, when it should omit the collector like `internals.state(server.root).knexGroup.knex` right? I found this because I was trying to update a branch of [user-boilerplate](https://github.com/mattboutet/user-boilerplate) to use this branch of schwifty, and ran into some problems, it's weird that it passes all schwifty tests though, so I dunno what's going on. If I get it in a decent place that can focus on the problem, maybe I could push that code up and get some help in here, I'll link it if I can't figure it out

Comment (devinivy) [reply lib/index.js:85]: Ahh I see!  Yes, this seems like a bug.  I believe that's actually one of the untested lines, which is why the tests pass.  Will fix.  Nice find!

Comment (wswoodruff) [reply lib/index.js:85]: Sweet!

Comment (devinivy) [reply lib/index.js:85]: This is being fixed in the next PR.  I logged a bug for it: #16.
